import { Montserrat } from 'next/font/google';
import { Protest_Revolution } from 'next/font/google';
import "../styles/globals.css";

export const metadata = {
  title: "Sayantan's Portfolio",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
});

const protestRevolution = Protest_Revolution({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-protest-revolution',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${protestRevolution.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}